image: python:3.10-slim

stages:
  - test

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"

before_script:
  - echo "CI_JOB_TOKEN=${CI_JOB_TOKEN:0:4}****"
  - python -m venv venv
  - . venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

test_bot:
  stage: test
  tags:
    - docker
  script:
    - timeout 5s python -c "import luncher.main"
 